version: "3.8"

services:
  api:
    build: ./api
    ports:
      - "3333:3333"
    volumes:
      - ./api:/api:rw

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/frontend:rw
